BADGER_PATH:
  BADGER_PLUGIN_ROOT:
    value: null
  BADGER_DB_ROOT:
    value: null
  BADGER_LOGBOOK_ROOT:
    value: null
  BADGER_ARCHIVE_ROOT:
    value: null

BADGER_CORE:
  BADGER_DATA_DUMP_PERIOD:
    default_value: 1

BADGER_GUI:
  BADGER_THEME:
    value: "dark"
  BADGER_ENABLE_ADVANCED:
    value: false
