name: Test PyPI build

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow || github.ref }}
  cancel-in-progress: true

jobs:
  test-pypi-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: |
          python -m pip install build --user
      - name: Build a source tarball
        run: |
          python -m build --sdist --outdir dist/ .